title: Lei Zhang(张蕾)
position: Senior Engineer (Associate Senior Level)
affiliation: School of Physics, Northeast Normal University
email: zhangl179@nenu.edu.cn
email_link: mailto:zhangl179@nenu.edu.cn
github_link: https://github.com/zhanglei179
weixin: ./assets/img/weixin.png
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description:  A Senior Engineer at the School of Physics, Northeast Normal University (NENU)
remote_theme: yaoyao-liu/strata-academic
